### ISSUE TITLE
Immediate Crash Happening 1.18.1

### ISSUE THREAD

**Issue by zachsai** [Thelnfamous1/Sapience#8] opened 2021-12-19 20:17 UTC
https://pastebin.com/cywdKWFz

**Comment by esotericist** [comment] 2021-12-19 21:51
duplicate of #7

**Comment by Thelnfamous1** [comment] 2021-12-21 21:48
Fixing now, sorry about this guys!

**Comment by Thelnfamous1** [comment] 2021-12-21 21:49
#7, check here for updates

**Closed as completed** 2021-12-21 22:19 UTC
